use  dorny/test-reporter@v1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,5 +32,16 @@ jobs:
       - name: Run tests
         run: yarn test
       
-      - name: Jest coverage report
-        uses: ArtiomTr/jest-coverage-report-action@v2.2.4
+      - name: Check files
+        run: ls -la
+      
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: coverage/coverage-final.json    # Path to test results
+          reporter: jest-junit        # Format of test results
+      
+      # - name: Jest coverage report
+      #   uses: ArtiomTr/jest-coverage-report-action@v2.2.4
